import { ShieldHalf } from "lucide-react";
import { PrintField, PrintSection } from "@/components/reports/print-field";
import { formatDuration, formatTimestamp } from "@/lib/format";
import { buildReportNarrative } from "@/lib/report-summary";
import type { Report } from "@/lib/types";

export function ReportDocument({ report }: { report: Report }) {
  const narrative = buildReportNarrative(report);
  const succeeded = report.status === "completed";

  return (
    <div
      id="jocky-print-root"
      className="mx-auto w-full max-w-[210mm] rounded-sm border border-neutral-300 bg-white px-10 py-10 text-neutral-900 shadow-2xl print:m-0 print:max-w-none print:rounded-none print:border-0 print:shadow-none"
    >
      <header className="flex items-start justify-between border-b-2 border-neutral-900 pb-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded border-2 border-neutral-900">
            <ShieldHalf className="h-5 w-5" strokeWidth={2} />
          </div>
          <div>
            <p className="text-[15pt] font-bold tracking-tight">JOCKY</p>
            <p className="text-[8.5pt] font-medium uppercase tracking-widest text-neutral-600">
              Digital Forensics Analysis Report
            </p>
          </div>
        </div>
        <div className="text-right text-[9pt] text-neutral-600">
          <p className="font-mono font-semibold text-neutral-900">{report.report_id}</p>
          <p>{formatTimestamp(report.timestamp)}</p>
        </div>
      </header>

      <div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">
        <PrintField label="Command" value={report.command} mono />
        <PrintField label="Action" value={report.action ?? "—"} mono />
        <PrintField label="Target" value={report.target ?? "—"} mono />
        <PrintField
          label="Status"
          value={
            <span className={succeeded ? "text-green-700" : "text-red-700"}>
              {report.status.toUpperCase()}
            </span>
          }
        />
      </div>
      <div className="mt-3 grid grid-cols-2 gap-4 sm:grid-cols-4">
        <PrintField label="Execution Time" value={formatDuration(report.execution_time_ms)} mono />
      </div>

      <PrintSection title="Executive Summary">
        <p className="text-[10pt] leading-relaxed text-neutral-800">{narrative.summary}</p>
      </PrintSection>

      {narrative.evidence.length > 0 && (
        <PrintSection title="Evidence">
          <div className="space-y-2">
            {narrative.evidence.map((item) => (
              <PrintField key={item.label} label={item.label} value={item.value} mono />
            ))}
          </div>
        </PrintSection>
      )}

      {narrative.findings.length > 0 && (
        <PrintSection title="Findings">
          <ul className="list-disc space-y-1 pl-5 text-[9.5pt] leading-relaxed text-neutral-800">
            {narrative.findings.map((finding, i) => (
              <li key={i}>{finding}</li>
            ))}
          </ul>
        </PrintSection>
      )}

      <PrintSection title="Verification">
        <p className="text-[9.5pt] leading-relaxed text-neutral-800">{narrative.verification}</p>
      </PrintSection>

      {(report.warnings.length > 0 || report.errors.length > 0) && (
        <PrintSection title="Warnings">
          {report.warnings.length === 0 && report.errors.length === 0 ? (
            <p className="text-[9.5pt] text-neutral-500">None.</p>
          ) : (
            <ul className="list-disc space-y-1 pl-5 text-[9.5pt] leading-relaxed text-red-700">
              {[...report.errors, ...report.warnings].map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
          )}
        </PrintSection>
      )}

      <footer className="mt-10 border-t border-neutral-300 pt-3 text-center text-[8pt] text-neutral-500">
        Generated by JOCKY — Digital Forensics Investigation Platform · Defensive analysis only ·
        This report reflects automated, read-only observations and requires analyst review before
        use in any determination.
      </footer>
    </div>
  );
}
