APPLICATION_VERSION = "0.5.1"
BACKEND_VERSION = APPLICATION_VERSION
API_VERSION = 1
COMMAND_SCHEMA_VERSION = 1
REPORT_SCHEMA_VERSION = 4
DATABASE_SCHEMA_VERSION = 3


def versions():
    return {"application": APPLICATION_VERSION, "backend": BACKEND_VERSION,
            "api": API_VERSION, "command_schema": COMMAND_SCHEMA_VERSION,
            "report_schema": REPORT_SCHEMA_VERSION, "database_schema": DATABASE_SCHEMA_VERSION}
